name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - oldstable
          - stable

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run go fmt
        run: test -z "$(gofmt -l .)"
        if: matrix.go-version == 'stable'

      - run: go test -covermode=atomic -coverprofile=coverage.out -race -v ./...
        env:
          TESTING_LOGGER_LEVEL: fatal

      - uses: codecov/codecov-action@v3
        if: matrix.go-version == 'stable'
